routes/web.php
<?php

use App\Http\Controllers\AssessmentController;
use App\Http\Controllers\AssessmentResultController;
use App\Http\Controllers\CriteriaAssessmentController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MappingAlternativeController;
use App\Http\Controllers\SAWController;
use App\Http\Controllers\UserAssessmentController;
use App\Http\Controllers\UserAssessmentResponseController;
use App\Http\Controllers\WeightCriteriaController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('home');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/bobot', [SAWController::class, 'index'])->name('bobot');

// kriteria penilaian
Route::get('kriteria-penilaian', [AssessmentController::class, 'index'])->name('kriteria-penilaian');
Route::get('kriteria-penilaian/create', [AssessmentController::class, 'create'])->name('kriteria-penilaian-create');
Route::post('kriteria-penilaian/create', [AssessmentController::class, 'store'])->name('kriteria-penilaian-store');
Route::get('kriteria-penilaian/{id}/edit', [AssessmentController::class, 'show'])->name('kriteria-penilaian-show');
Route::put('kriteria-penilaian/{id}/edit', [AssessmentController::class, 'update'])->name('kriteria-penilaian-update');
Route::get('kriteria-penilaian/{id}/review', [CriteriaAssessmentController::class, 'show'])->name('kriteria-penilaian-review-show');
Route::put('kriteria-penilaian/{id}/review', [CriteriaAssessmentController::class, 'update'])->name('kriteria-penilaian-review-update');
Route::get('kriteria-penilaian/{id}/preview', [CriteriaAssessmentController::class, 'edit'])->name('kriteria-penilaian-preview-show');
Route::get('kriteria-penilaian/{id}/publish', [AssessmentController::class, 'publish'])->name('kriteria-penilaian-publish');
Route::get('kriteria-penilaian/{id}/unpublish', [AssessmentController::class, 'unpublish'])->name('kriteria-penilaian-unpublish');

Route::get('bobot-kriteria', [WeightCriteriaController::class, 'index'])->name('bobot-kriteria-index');
Route::get('bobot-kriteria/{id}/generate', [WeightCriteriaController::class, 'getWeight'])->name('bobot-kriteria-generate');

// mapping alternative
Route::get('mapping-alternatif', [MappingAlternativeController::class, 'index'])->name('mapping-alternative-index');
Route::post('mapping-alternatif', [MappingAlternativeController::class, 'store'])->name('mapping-alternative-store');
Route::delete('mapping-alternatif/{id}', [MappingAlternativeController::class, 'destroy'])->name('mapping-alternative-destroy');

// penilaian alternatif
Route::get('/penilaian-alternatif', [UserAssessmentController::class, 'index'])->name('penilaian-alternatif-index');
Route::get('/penilaian-alternatif/{assessmentId}/{userId}', [UserAssessmentController::class, 'show'])->name('penilaian-alternatif-show');
Route::put('/penilaian-alternatif/{assessmentId}/{userId}', [UserAssessmentController::class, 'update'])->name('penilaian-alternatif-update');
Route::get('/penilaian-response', [UserAssessmentResponseController::class, 'index'])->name('response-penilaian-index');

// penilaian
Route::get('/rank-penilaian', [AssessmentResultController::class, 'index'])->name('penilaian-result-index');

app/Models/User.php
<?php

namespace App\Models;

use App\Constants\Role;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
        'division_id',
        'job_id',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getIsRoleManagementAttribute(): bool
    {
        return $this->role === Role::ROLE_MANAGEMENT;
    }

    public function division()
    {
        return $this->hasOne(Division::class, 'id', 'division_id');
    }

    public function job()
    {
        return $this->hasOne(Job::class, 'id', 'job_id');
    }
}

resources/views/layouts/app-blank.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title') - {{ config('app.name', 'Penilaian Kinerja Karyawan') }}</title>

    <!-- Scripts -->
    {{--<script src="{{ asset('js/app.js') }}" defer></script>--}}

    <!-- base:css -->
    <link rel="stylesheet" href="{{ asset('vendors/typicons.font/font/typicons.css') }}">
    <link rel="stylesheet" href="{{ asset('vendors/css/vendor.bundle.base.css') }}">
    <!-- plugin css for this page -->
    @yield('css-plugins')

    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="shortcut icon" href="{{ asset('images/favicon.png') }}"/>

    @yield('styles')
</head>
<body>
<div id="app">
    <div class="container-scroller">
        <!-- partial -->
        <div class="container-fluid page-body-wrapper full-page-wrapper">
            @yield('content')
        </div>
        <!-- page-body-wrapper ends -->
    </div>

    <!-- container-scroller -->
    <!-- base:js -->
    <script src="{{ asset('vendors/js/vendor.bundle.base.js') }}"></script>
    <!-- endinject -->
    <!-- Plugin js for this page-->
    <!-- End plugin js for this page-->
    <!-- inject:js -->
    <script src="{{ asset('js/off-canvas.js') }}"></script>
    <script src="{{ asset('js/hoverable-collapse.js') }}"></script>
    <script src="{{ asset('js/template.js') }}"></script>
    <script src="{{ asset('js/settings.js') }}"></script>
    <script src="{{ asset('js/todolist.js') }}"></script>
    <!-- endinject -->
    <!-- plugin js for this page -->
    <script src="{{ asset('vendors/progressbar.js/progressbar.min.js') }}"></script>
    <script src="{{ asset('vendors/chart.js/Chart.min.js') }}"></script>
    <!-- End plugin js for this page -->
    <!-- Custom js for this page-->
    <script src="{{ asset('js/dashboard.js') }}"></script>
    <!-- End custom js for this page-->

    @stack('scripts')
</div>
</body>
</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title') - {{ config('app.name', 'Penilaian Kinerja Karyawan') }}</title>

    <!-- base:css -->
    <link rel="stylesheet" href="{{ asset('vendors/typicons.font/font/typicons.css') }}">
    <link rel="stylesheet" href="{{ asset('vendors/select2/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('vendors/select2-bootstrap-theme/select2-bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('vendors/css/vendor.bundle.base.css') }}">
    <link rel="stylesheet" href="{{ asset('vendors/data-tables/datatables.min.css') }}">
    <!-- plugin css for this page -->
    @yield('css-plugins')
    <style>
        .cursor-pointer {
            cursor: pointer !important;
        }

        .select2-container--default .select2-selection--single .select2-selection__arrow {
            top: 8px;
        }

        .gap-1 {
            gap: 2px;
        }

        .gap-2 {
            gap: 4px;
        }

        .gap-3 {
            gap: 6px;
        }

        .gap-4 {
            gap: 8px;
        }

        .cursor-move {
            cursor: move;
        }

        .badge-warning {
            color: white !important;
        }
    </style>

    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="shortcut icon" href="{{ asset('images/favicon.png') }}"/>

    @yield('styles')
</head>
<body class="sidebar-light">
<div id="app">
    <div class="container-scroller">
        @include('layouts.header')

        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            {{--@include('layouts.sidebar-setting')--}}
            @include('layouts.sidebar')


            <div class="main-panel">
                <div class="content-wrapper">
                    @yield('content')
                </div>

                <footer class="footer">
                    <div class="d-sm-flex justify-content-center justify-content-sm-between">
                        <span class="text-center text-sm-left d-block d-sm-inline-block">
                            Copyright ©
                            <a href="#">Maulana Yusup | 14177015</a>
                            - 2023
                        </span>
                        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">
                            Aplikasi <strong>Penilaian Kinerja Karyawan</strong> Metode <strong>Simple Additive Weighting</strong>
                        </span>
                    </div>
                </footer>
            </div>
        </div>
    </div>

    <script src="{{ asset('vendors/js/vendor.bundle.base.js') }}"></script>
    <script src="{{ asset('js/app.js') }}"></script>
    <!-- Plugin js for this page-->
    <script src="{{ asset('vendors/jquery-ui/jquery-ui.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('js/off-canvas.js') }}"></script>
    <script src="{{ asset('js/hoverable-collapse.js') }}"></script>
    <script src="{{ asset('js/template.js') }}"></script>
    <script src="{{ asset('js/settings.js') }}"></script>
    <!-- plugin js for this page -->
    <script src="{{ asset('vendors/select2/select2.min.js') }}"></script>
    <script src="{{ asset('vendors/data-tables/datatables.min.js') }}"></script>

    <script>
        $(document).ready(function () {
            $('.textarea-height-auto').each(function (key, value) {
                value.style.overflow = 'hidden';
                value.style.height = 0;
                value.style.height = value.scrollHeight + 'px';
            });
        });

        $(document).on('keydown keyup keypress', '.textarea-height-auto', function () {
            this.style.overflow = 'hidden';
            this.style.height = 0;
            this.style.height = this.scrollHeight + 'px';
        });

        @if (Session::has('success'))
        Swal.fire({
            title: '{!! Session::get('success') !!}',
            text: '{!! Session::has('messages') ? Session::get('messages') : '' !!}',
            icon: 'success'
        });
        @endif
        @if (Session::has('error'))
        Swal.fire({
            title: '{!! Session::get('error') !!}',
            text: '{!! Session::has('messages') ? Session::get('messages') : '' !!}',
            icon: 'error'
        });
        @endif
        @if (Session::has('info'))
        Swal.fire({
            title: '{!! Session::get('info') !!}',
            text: '{!! Session::has('messages') ? Session::get('messages') : '' !!}',
            icon: 'info'
        });
        @endif
    </script>
    @stack('scripts')
</div>
</body>
</html>

resources/views/layouts/header.blade.php
<nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row navbar-info">
    <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
        <a class="navbar-brand brand-logo" href="#">
            <img src="{{ asset('images/logo.svg') }}" alt="logo"/>
        </a>
        <a class="navbar-brand brand-logo-mini" href="#">
            <img src="{{ asset('images/logo-mini.svg') }}" alt="logo"/>
        </a>
        <button
            class="navbar-toggler navbar-toggler align-self-center d-none d-lg-flex"
            type="button"
            data-toggle="minimize">
            <span class="typcn typcn-th-menu"></span>
        </button>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
        <ul class="navbar-nav navbar-nav-right">
            <li class="nav-item dropdown d-flex mr-2">
                <a class="nav-link count-indicator dropdown-toggle d-flex align-items-center justify-content-center"
                   id="notificationDropdown" href="#" data-toggle="dropdown">
                    <i class="typcn typcn-bell mr-0"></i>
                    @if(isset($totalAssessmentNotification) && $totalAssessmentNotification > 0)
                        <span class="count bg-danger">{{ $totalAssessmentNotification }}</span>
                    @endif
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list"
                     aria-labelledby="notificationDropdown">
                    @if($totalAssessmentNotification == 0)
                        <p class="mb-0 font-weight-normal float-left dropdown-header">Belum ada pemberitahuan</p>
                    @endif
                    @if(isset($teamAssessmentList) && count($teamAssessmentList) > 0)
                        <p class="mb-0 font-weight-normal float-left dropdown-header">Beri Penilaian Kriteria</p>
                        @foreach($teamAssessmentList as $assessment)
                            <a class="dropdown-item preview-item cursor-pointer"
                               href="{{ route('kriteria-penilaian-review-show', ['id' => $assessment->id]) }}">
                                <div class="preview-thumbnail">
                                    <div class="preview-icon bg-behance" style="width: 25px; height: 25px;">
                                        <i class="typcn typcn-puzzle mx-0"></i>
                                    </div>
                                </div>
                                <div class="preview-item-content">
                                    <h6 class="preview-subject font-weight-bold">{{ $assessment->title }}</h6>
                                    <p class="font-weight-light text-small mb-0">
                                        {{ $assessment->created_at->diffForHumans() }}
                                    </p>
                                </div>
                            </a>
                        @endforeach
                    @endif
                    @if(isset($userAssessmentList) && count($userAssessmentList) > 0)
                        <p class="mb-0 font-weight-normal float-left dropdown-header">Beri Penilaian Alternatif</p>
                        @foreach($userAssessmentList as $assessments)
                            <p class="mb-0 font-weight-normal text-small float-left dropdown-header py-0 font-italic">
                                {{ $assessments->title }}
                            </p>
                            @foreach($assessments->userAssessments as $userAssessment)
                                <a class="dropdown-item preview-item cursor-pointer"
                                   href="{{ route('penilaian-alternatif-show', [$assessments->id, $userAssessment->user_id]) }}">
                                    <div class="preview-thumbnail">
                                        <div class="preview-icon bg-linkedin" style="width: 25px; height: 25px;">
                                            <i class="typcn typcn-user mx-0"></i>
                                        </div>
                                    </div>
                                    <div class="preview-item-content">
                                        <h6 class="preview-subject font-weight-bold">
                                            {{ $userAssessment->user->name }}
                                        </h6>
                                        <p class="font-weight-light text-small mb-0">
                                            {{ $assessments->created_at->diffForHumans() }}
                                        </p>
                                    </div>
                                </a>
                            @endforeach
                        @endforeach
                    @endif
                </div>
            </li>
            <li class="nav-item ml-3">
                <a class="nav-link pl-0 pr-0" href="{{ route('logout') }}"
                   onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                    <span class="nav-profile-name">{{ __('Logout') }}</span>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                        @csrf
                    </form>
                </a>
            </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button"
                data-toggle="offcanvas">
            <span class="typcn typcn-th-menu"></span>
        </button>
    </div>
</nav>

resources/views/layouts/sidebar-setting.blade.php
<div class="theme-setting-wrapper">
    <div id="settings-trigger"><i class="typcn typcn-cog-outline"></i></div>
    <div id="theme-settings" class="settings-panel">
        <i class="settings-close typcn typcn-delete-outline"></i>
        <p class="settings-heading">SIDEBAR SKINS</p>
        <div class="sidebar-bg-options selected" id="sidebar-light-theme">
            <div class="img-ss rounded-circle bg-light border mr-3"></div>
            Light
        </div>
        <div class="sidebar-bg-options" id="sidebar-dark-theme">
            <div class="img-ss rounded-circle bg-dark border mr-3"></div>
            Dark
        </div>
        <p class="settings-heading mt-2">HEADER SKINS</p>
        <div class="color-tiles mx-0 px-4">
            <div class="tiles success"></div>
            <div class="tiles warning"></div>
            <div class="tiles danger"></div>
            <div class="tiles primary"></div>
            <div class="tiles info"></div>
            <div class="tiles dark"></div>
            <div class="tiles default border"></div>
        </div>
    </div>
</div>

resources/views/layouts/sidebar.blade.php
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        <li class="nav-item">
            <div class="d-flex sidebar-profile">
                <div class="sidebar-profile-image">
                    <img src="{{ asset('images/samples/300x300/1.jpg') }}" alt="image">
                    <span class="sidebar-status-indicator"></span>
                </div>
                <div class="sidebar-profile-name">
                    <p class="sidebar-name">
                        {{ auth()->user()->name }}
                    </p>
                    <p class="sidebar-designation">
                        {{ auth()->user()->email }}
                    </p>
                </div>
            </div>
        </li>
        <li class="nav-item  {{ request()->routeIs('home') ? 'active' : '' }}">
            <a class="nav-link" href="{{ route('home') }}">
                <i class="typcn typcn-device-desktop menu-icon"></i>
                <span class="menu-title">Home</span>
            </a>
        </li>
        <li class="nav-item {{ request()->routeIs('penilaian-alternatif*') ? 'active' : '' }}">
            <a class="nav-link" href="{{ route('penilaian-alternatif-index') }}">
                <i class="typcn typcn-document-text menu-icon"></i>
                <span class="menu-title">Penilaian Alternatif</span>
            </a>
        </li>
        @if(auth()->user()->is_role_management)
            <li class="nav-item">
                <p class="sidebar-menu-title">Master</p>
            </li>
            <li class="nav-item {{ request()->routeIs('kriteria-penilaian*') ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('kriteria-penilaian') }}">
                    <i class="typcn typcn-puzzle-outline menu-icon"></i>
                    <span class="menu-title">Kriteria Penilaian</span>
                </a>
            </li>
            <li class="nav-item {{ request()->routeIs('bobot-kriteria-index*') ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('bobot-kriteria-index') }}">
                    <i class="typcn typcn-puzzle menu-icon"></i>
                    <span class="menu-title">Bobot Kriteria</span>
                </a>
            </li>
            <li class="nav-item {{ request()->routeIs('mapping-alternative-index*') ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('mapping-alternative-index') }}">
                    <i class="typcn typcn-group menu-icon"></i>
                    <span class="menu-title">Mapping Alternatif</span>
                </a>
            </li>
            <li class="nav-item {{ request()->routeIs('response-penilaian-index*') ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('response-penilaian-index') }}">
                    <i class="typcn typcn-database menu-icon"></i>
                    <span class="menu-title">Semua Penilaian</span>
                </a>
            </li>
            <li class="nav-item {{ request()->routeIs('penilaian-result-index*') ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('penilaian-result-index') }}">
                    <i class="typcn typcn-chart-line menu-icon"></i>
                    <span class="menu-title">Peringkat Alternatif</span>
                </a>
            </li>
        @endif
    </ul>
</nav>