routes/web.php
<?php

use App\Http\Controllers\AssessmentController;
use App\Http\Controllers\AssessmentResultController;
use App\Http\Controllers\CriteriaAssessmentController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MappingAlternativeController;
use App\Http\Controllers\SAWController;
use App\Http\Controllers\UserAssessmentController;
use App\Http\Controllers\UserAssessmentResponseController;
use App\Http\Controllers\WeightCriteriaController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('home');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/bobot', [SAWController::class, 'index'])->name('bobot');

// kriteria penilaian
Route::get('kriteria-penilaian', [AssessmentController::class, 'index'])->name('kriteria-penilaian');
Route::get('kriteria-penilaian/create', [AssessmentController::class, 'create'])->name('kriteria-penilaian-create');
Route::post('kriteria-penilaian/create', [AssessmentController::class, 'store'])->name('kriteria-penilaian-store');
Route::get('kriteria-penilaian/{id}/edit', [AssessmentController::class, 'show'])->name('kriteria-penilaian-show');
Route::put('kriteria-penilaian/{id}/edit', [AssessmentController::class, 'update'])->name('kriteria-penilaian-update');
Route::get('kriteria-penilaian/{id}/review', [CriteriaAssessmentController::class, 'show'])->name('kriteria-penilaian-review-show');
Route::put('kriteria-penilaian/{id}/review', [CriteriaAssessmentController::class, 'update'])->name('kriteria-penilaian-review-update');
Route::get('kriteria-penilaian/{id}/preview', [CriteriaAssessmentController::class, 'edit'])->name('kriteria-penilaian-preview-show');
Route::get('kriteria-penilaian/{id}/publish', [AssessmentController::class, 'publish'])->name('kriteria-penilaian-publish');
Route::get('kriteria-penilaian/{id}/unpublish', [AssessmentController::class, 'unpublish'])->name('kriteria-penilaian-unpublish');

Route::get('bobot-kriteria', [WeightCriteriaController::class, 'index'])->name('bobot-kriteria-index');
Route::get('bobot-kriteria/{id}/generate', [WeightCriteriaController::class, 'getWeight'])->name('bobot-kriteria-generate');

// mapping alternative
Route::get('mapping-alternatif', [MappingAlternativeController::class, 'index'])->name('mapping-alternative-index');
Route::post('mapping-alternatif', [MappingAlternativeController::class, 'store'])->name('mapping-alternative-store');
Route::delete('mapping-alternatif/{id}', [MappingAlternativeController::class, 'destroy'])->name('mapping-alternative-destroy');

// penilaian alternatif
Route::get('/penilaian-alternatif', [UserAssessmentController::class, 'index'])->name('penilaian-alternatif-index');
Route::get('/penilaian-alternatif/{assessmentId}/{userId}', [UserAssessmentController::class, 'show'])->name('penilaian-alternatif-show');
Route::put('/penilaian-alternatif/{assessmentId}/{userId}', [UserAssessmentController::class, 'update'])->name('penilaian-alternatif-update');
Route::get('/penilaian-response', [UserAssessmentResponseController::class, 'index'])->name('response-penilaian-index');

// penilaian
Route::get('/rank-penilaian', [AssessmentResultController::class, 'index'])->name('penilaian-result-index');

app/Http/Controllers/AssessmentController.php
<?php

namespace App\Http\Controllers;

use App\Constants\AssessmentStatus;
use App\Constants\Fields;
use App\Models\Assessment;
use App\Models\AssessmentTeam;
use App\Models\User;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;

class AssessmentController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $data = Assessment::query()
            ->with(['createBy', 'updateBy', 'teams.user', 'teams.reviews'])
            ->withCount([
                'items' => function ($query) {
                    $query->whereNotIn('field_type', [Fields::TITLE, Fields::INPUT_PARAGRAPH]);
                }
            ])
            ->where(function ($query) {
                $query->whereHas('teams', function (Builder $query) {
                    $query->where('user_id', auth()->id());
                });
                $query->orWhere('created_by', auth()->id());
            })
            ->get();

        return view('pages.assessment-criteria.index', ['data' => $data]);
    }

    public function create()
    {
        $users = User::query()
            ->with(['division', 'job'])
            ->select('id', 'name', 'division_id', 'job_id')
//            ->where('id', '<>', auth()->id())
            ->get();
        return view('pages.assessment-criteria.create', [
            'users' => $users,
        ]);
    }

    public function store(Request $request)
    {
        // TODO: add validation
        $assessment = Assessment::query()->create([
            'title' => $request->get('title'),
            'description' => $request->get('description'),
            'status' => AssessmentStatus::PENDING,
        ]);
        $assessment->teams()->createMany(array_map(function ($value) use ($assessment) {
            return ['user_id' => $value];
        }, $request->get('teams')));
        return redirect()->route('kriteria-penilaian-show', ['id' => $assessment->id]);
    }

    public function show($id)
    {
        $assessment = Assessment::query()
            ->with(['teams', 'items'])
            ->where(function ($query) {
                $query->whereHas('teams', function (Builder $query) {
                    $query->where('user_id', auth()->id());
                });
                $query->orWhere('created_by', auth()->id());
            })
            ->findOrFail($id);

        $users = User::query()
            ->with(['division', 'job'])
            ->select('id', 'name', 'division_id', 'job_id')
            ->get();
        $selectedTeams = $assessment->teams->pluck('user_id');

        return view('pages.assessment-criteria.edit', [
            'assessment' => $assessment,
            'selectedTeams' => $selectedTeams,
            'users' => $users,
        ]);
    }

    public function edit($id)
    {
        return $assessment = Assessment::query()
            ->with('teams')
            ->where(function ($query) {
                $query->whereHas('teams', function (Builder $query) {
                    $query->where('user_id', auth()->id());
                });
                $query->orWhere('created_by', auth()->id());
            })
            ->findOrFail($id);
    }

    public function update(Request $request, $id)
    {
        $assessment = Assessment::query()
            ->with(['teams', 'items'])
            ->where(function ($query) {
                $query->whereHas('teams', function (Builder $query) {
                    $query->where('user_id', auth()->id());
                });
                $query->orWhere('created_by', auth()->id());
            })
            ->findOrFail($id);

        $teams = $request->get('teams');
        $assessment->teams()->whereNotIn('user_id', $teams)->delete();
        foreach ($teams as $id) {
            $team = $assessment->teams()->where('user_id', $id)->first();
            if (!$team) {
                $assessment->teams()->create(['user_id' => $id]);
            }
        }

        $hasNewItem = false;
        $assessmentItemIds = [];
        foreach ($request->get('items', []) as $key => $item) {
            $itemId = $item['id'] ?? null;
            $data = [
                'title' => $item['title'],
                'description' => $item['description'] ?? null,
                'cost_benefit' => $item['cost_benefit'] ?? null,
                'field_type' => $item['type'],
                'field_value' => json_encode($item['value']) ?? null,
                'group' => $item['group'] ?? null,
                'ordinal_no' => $key + 1,
            ];
            if ($itemId == null) {
                $hasNewItem |= in_array($item['type'], [Fields::INPUT_LINEAR_SCALE, Fields::INPUT_NUMBER]);
                $itemAssessment = $assessment->items()->create($data);
                $assessmentItemIds[] = $itemAssessment->id;
                continue;
            }
            $itemAssessment = $assessment->items()->find($itemId);
            if ($itemAssessment) {
                $itemAssessment->update($data);
                $assessmentItemIds[] = $itemAssessment->id;
            }
        }
        $assessment->items()->whereNotIn('id', $assessmentItemIds)->delete();

        $assessment->title = $request->get('title');
        $assessment->description = $request->get('description');
        if ($hasNewItem) {
            $assessment->teamAssessmentReviews()->delete();
            $assessment->status = AssessmentStatus::REVIEW_BY_TEAMS;
        }
        $assessment->weight = null;
        $assessment->update();

        return [
            'success' => true,
            'message' => 'Berhasil menyimpan',
            'data' => $assessment
        ];
    }

    public function destroy($id)
    {
        //
    }

    public function publish($id)
    {
        $assessment = Assessment::query()
            ->with('teams')
            ->where(function ($query) {
                $query->whereHas('teams', function (Builder $query) {
                    $query->where('user_id', auth()->id());
                });
                $query->orWhere('created_by', auth()->id());
            })
            ->find($id);

        if (!$assessment) {
            return redirect()->back();
        }

        if ($assessment->status != AssessmentStatus::MAPPING_USERS) {
            return redirect()
                ->back()
                ->with('error', 'Gagal!');
        }

        $assessment->update([
            'status' => AssessmentStatus::PUBLISHED
        ]);

        return redirect()
            ->back()
            ->with('success', 'Berhasil!')
            ->with('messages', 'Berhasil dipublikasi.');
    }

    public function unpublish($id)
    {
        $assessment = Assessment::query()
            ->with('userAssessmentReviews')
            ->where(function ($query) {
                $query->whereHas('teams', function (Builder $query) {
                    $query->where('user_id', auth()->id());
                });
                $query->orWhere('created_by', auth()->id());
            })
            ->find($id);

        if (!$assessment) {
            return redirect()->back();
        }

        if ($assessment->status != AssessmentStatus::PUBLISHED) {
            return redirect()
                ->back()
                ->with('error', 'Gagal!');
        }

        $assessment->userAssessmentReviews()->delete();

        $assessment->update([
            'status' => AssessmentStatus::MAPPING_USERS
        ]);

        return redirect()
            ->back()
            ->with('success', 'Berhasil!')
            ->with('messages', 'Berhasil batalkan publikasi.');
    }
}

resources/views/pages/assessment-criteria/create.blade.php
@extends('layouts.app')

@section('title', 'Tambah Kriteria Penilaian')

@section('css-plugins')
@endsection

@section('styles')
    <style>
        .form-group {
            margin-bottom: 10px;
        }

        .cursor-move {
            cursor: move;
        }
    </style>
@endsection

@section('content')
    <form action="{{ route('kriteria-penilaian-store') }}" method="POST">
        @csrf
        <div class="row mt-3">
            <div class="col-lg-8 offset-lg-2">
                <div class="w-100 d-flex flex-column">
                    <div class="card">
                        <div class="card-body">
                            <div class="form-group">
                                <input
                                    type="text"
                                    name="title"
                                    class="form-control card-title mb-0"
                                    required
                                    placeholder="Judul Penilaian">
                            </div>
                            <div class="form-group">
                            <textarea
                                name="description"
                                class="form-control textarea-height-auto"
                                placeholder="Deskripsi Penilaian"
                                rows="1"></textarea>
                            </div>

                            <hr>

                            <div class="form-group">
                                <label>Tim Penilai</label>
                                <select class="select-teams w-100" name="teams[]" multiple required>
                                    @foreach($users as $user)
                                        <option value="{{ $user->id }}">{{ $user->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="text-right mt-4">
                        <button class="btn btn-inverse-primary">
                            Simpan
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection


@push('scripts')
    <script>
        $(document).ready(function () {
            $(".select-teams").select2();

            $('.textarea-height-auto').each(function (key, value) {
                value.style.overflow = 'hidden';
                value.style.height = 0;
                value.style.height = value.scrollHeight + 'px';
            });
        });

        $(document).on('keydown keyup keypress', '.textarea-height-auto', function () {
            this.style.overflow = 'hidden';
            this.style.height = 0;
            this.style.height = this.scrollHeight + 'px';
        });
    </script>
@endpush

resources/views/pages/assessment-criteria/index.blade.php
@extends('layouts.app')

@section('title', 'Kriteria Penilaian')

@section('css-plugins')
@endsection

@section('styles')
@endsection

@section('content')
    <div class="row">
        <div class="offset-sm-6 col-sm-6">
            <div class="d-flex align-items-center justify-content-end">
                <div class="pr-1 mb-3 mr-2 mb-xl-0">
                    <button type="button" class="btn btn-sm bg-white btn-icon-text border"><i
                            class="typcn typcn-arrow-forward-outline mr-2"></i>Import
                    </button>
                </div>
                <div class="pr-1 mb-3 mb-xl-0">
                    <button type="button" class="btn btn-sm bg-white btn-icon-text border"><i
                            class="typcn typcn-info-large-outline mr-2"></i>info
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex justify-content-between mb-3">
                        <h4 class="card-title">Kriteria Penilaian</h4>
                        <a type="button" href="{{ route('kriteria-penilaian-create') }}" class="btn btn-outline-info">
                            Tambah Data
                        </a>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-hover table-sm">
                            <thead>
                            <tr>
                                <th>Judul</th>
                                <th>Tim Penilai</th>
                                <th>Status</th>
                                <th>Aksi</th>
                            </tr>
                            </thead>
                            <tbody>
                            @if(count($data) == 0)
                                <tr>
                                    <td colspan="4" class="text-center">Belum ada data</td>
                                </tr>
                            @endif
                            @foreach($data as $item)
                                @php
                                    $needReview = false;
                                @endphp
                                <tr>
                                    <td class="valign-top" style="width: 300px;">
                                        <b>{{ $item->title }}</b>
                                        @if($item->description)
                                            <div class="text-ellipsis-4">{{ $item->description }}</div>
                                        @endif
                                    </td>
                                    <td class="valign-top">
                                        @if($item->teams)
                                            <ul class="m-0">
                                                @foreach($item->teams as $team)
                                                    <li>
                                                        {{ $team->user->name }}
                                                        @if($item->status > \App\Constants\AssessmentStatus::PENDING)
                                                            @if($item->items_count == count($team->reviews))
                                                                <i class="typcn typcn-tick text-success my-auto"
                                                                   style="cursor: help; font-size: 20px;"
                                                                   title="Sudah Menilai"></i>
                                                            @else
                                                                @php
                                                                    if (auth()->id() == $team->user_id && $item->status == \App\Constants\AssessmentStatus::REVIEW_BY_TEAMS) {
                                                                        $needReview = true;
                                                                    }
                                                                @endphp
                                                            @endif
                                                        @endif
                                                    </li>
                                                @endforeach
                                            </ul>
                                        @else
                                            Kosong
                                        @endif
                                    </td>
                                    <td class="valign-top">
                                        <p>Dibuat oleh: {{ $item->createBy->name }}</p>
                                        <p>Terakhir update: {{ $item->updated_at }}</p>
                                        @if($item->status == \App\Constants\AssessmentStatus::PENDING)
                                            <label class="badge badge-outline-danger">
                                                {{ \App\Constants\AssessmentStatus::LIST_OPTIONS[$item->status] }}
                                            </label>
                                        @elseif($item->status == \App\Constants\AssessmentStatus::REVIEW_BY_TEAMS)
                                            <label class="badge badge-danger">
                                                {{ \App\Constants\AssessmentStatus::LIST_OPTIONS[$item->status] }}
                                            </label>
                                        @elseif($item->status == \App\Constants\AssessmentStatus::MAPPING_USERS)
                                            <label class="badge badge-warning">
                                                {{ \App\Constants\AssessmentStatus::LIST_OPTIONS[$item->status] }}
                                            </label>
                                        @elseif($item->status == \App\Constants\AssessmentStatus::PUBLISHED)
                                            <label class="badge badge-info">
                                                {{ \App\Constants\AssessmentStatus::LIST_OPTIONS[$item->status] }}
                                            </label>
                                        @endif
                                    </td>
                                    <td class="valign-top d-flex flex-column">
                                        <a href="{{ route('kriteria-penilaian-show', ['id' => $item->id]) }}"
                                           class="btn btn-info btn-sm"
                                           style="font-size: 12px">
                                            Edit
                                        </a>
                                        @if($item->status > \App\Constants\AssessmentStatus::PENDING)
                                            <a href="{{ route('kriteria-penilaian-preview-show', ['id' => $item->id]) }}"
                                               class="btn btn-outline-success btn-sm mt-2"
                                               style="font-size: 12px">
                                                Preview
                                            </a>
                                        @endif
                                        @if($needReview)
                                            <a href="{{ route('kriteria-penilaian-review-show', ['id' => $item->id]) }}"
                                               class="btn btn-warning btn-sm mt-2 text-white"
                                               style="font-size: 12px">
                                                Beri Penilaian
                                            </a>
                                        @endif
                                        @if($item->status == \App\Constants\AssessmentStatus::MAPPING_USERS)
                                            <button type="button"
                                                    class="btn btn-success btn-sm mt-2 btn-publish"
                                                    style="font-size: 12px"
                                                    data-id="{{ $item->id }}">
                                                Publikasi
                                            </button>
                                        @endif
                                        @if($item->status == \App\Constants\AssessmentStatus::PUBLISHED)
                                            <button type="button"
                                                    class="btn btn-outline-danger btn-sm mt-2 btn-un-publish"
                                                    style="font-size: 12px"
                                                    data-id="{{ $item->id }}">
                                                Batal Publikasi
                                            </button>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection


@push('scripts')
    <script>
        $(document).ready(function () {
            $('.btn-publish').click(function () {
                const id = $(this).data('id');
                Swal.fire({
                    title: 'Apakah anda yakin?',
                    text: 'Setelah penilaian ini dipublikasikan, anda tidak dapat menambahkan kembali kriteria baru.',
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Publikasi',
                    cancelButtonText: 'Tutup'
                }).then((result) => {
                    if (result.isConfirmed) {
                        window.location = '{{ route('kriteria-penilaian-publish', ['id' => ':id']) }}'.replace(':id', id);
                    }
                });
            });
            $('.btn-un-publish').click(function () {
                const id = $(this).data('id');
                Swal.fire({
                    title: 'Apakah anda yakin?',
                    text: 'Penilaian Alternatif yang sebelumnya telah dilakukan, akan ter-reset.',
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Ya, Batal Publikasi',
                    cancelButtonText: 'Tutup'
                }).then((result) => {
                    if (result.isConfirmed) {
                        window.location = '{{ route('kriteria-penilaian-unpublish', ['id' => ':id']) }}'.replace(':id', id);
                    }
                });
            });
        });
    </script>
@endpush

resources/views/pages/assessment-criteria/preview.blade.php
@extends('layouts.app')

@section('title', 'Tambah Kriteria Penilaian')

@section('css-plugins')
@endsection

@section('styles')
    <style>
    </style>
@endsection

@section('content')
    <div class="row mt-3">
        <div class="col-lg-8 offset-lg-2">
            @include('pages.others.form')
        </div>
    </div>
@endsection


@push('scripts')
    <script>
        $(document).ready(function () {
            $('.textarea-height-auto').each(function (key, value) {
                value.style.overflow = 'hidden';
                value.style.height = 0;
                value.style.height = value.scrollHeight + 'px';
            });
        });

        $(document).on('keydown keyup keypress', '.textarea-height-auto', function () {
            this.style.overflow = 'hidden';
            this.style.height = 0;
            this.style.height = this.scrollHeight + 'px';
        });
    </script>
@endpush